name: Deploy to EC2
on:
  push:
    branches:
      - main

env:
  # DEPLOYMENT VARIABLES
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_USER: ${{ secrets.EC2_USERNAME }}
  REMOTE_HOST: ${{ secrets.EC2_PUBLIC_IP }}
  TARGET: ${{ secrets.TARGET_DIR }}
  SOURCE: "./"
  EXCLUDE: /.git/, /.github/, .gitignore, README.md
  SCRIPT_AFTER: | 
    cd ${{ secrets.TARGET_DIR }}
    ls
    php artisan down
    php artisan migrate
    php artisan up
  # APP VARIABLE
  APP_NAME: ${{ secrets.APP_NAME }}
  APP_ENV: production
jobs:
  deploy:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     php-version: '8.0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v4.1.8
        # with:
          # key: ${{ env.SSH_PRIVATE_KEY }}
          # username: ubuntu
          # host: ec2-18-141-234-79.ap-southeast-1.compute.amazonaws.com
          # source: ./
          # target: /var/www/server
          # exclude: /.git/, /.github/, .gitignore, README.md
          # script_after: |
          #   cd /home/ec2-user/${{ env.APP_DIR }}
          #   npm install --production
          #   npm run migrate
          #   sudo pm2 restart app