name: Deploy to EC2
on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_USER: ${{ secrets.SSH_USERNAME }}
  REMOTE_HOST: ${{ secrets.SSH_HOST }}
  APP_NAME: ${{ secrets.APP_NAME }}
  APP_ENV: production
  # DATABASE VARIABLES
  DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  # SMTP VARIABLE   
jobs:
  deploy:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     php-version: '8.0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # - name: Create .env file
      #   run: |
      #     touch .env
      #     echo APP_NAME="$APP_NAME" >> .env
      #     echo APP_URL="$APP_URL" >> .env
      #     echo APP_PORT="$APP_PORT" >> .env
      #     echo APP_ENV="$APP_ENV" >> .env
          
      #     echo DB_CONNECTION="$DB_CONNECTION" >> .env
      #     echo DB_HOST="$DB_HOST" >> .env
      #     echo DB_PORT="$DB_PORT" >> .env
      #     echo DB_USER="$DB_USER" >> .env
      #     echo DB_PASSWORD="$DB_PASSWORD" >> .env
      #     echo DB_NAME="$DB_NAME" >> .env          
          
      #     echo "cat .env"
      #     cat .env
      #     echo "ls -a ."
      #     ls -a .

      #     echo "ls -a ${{ github.workspace }}"
      #     ls -a ${{ github.workspace }}
      #   shell: bash

      # - name: Install PHP and dependencies
      #   run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml

      # - name: Install Composer dependencies
      #   run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_PUBLIC_IP }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Clear SSH key
        run: rm ~/.ssh/id_rsa